// Generated by CoffeeScript 1.6.2
(function() {
  var client, mongodb, step;

  mongodb = require("mongodb");

  client = mongodb.MongoClient;

  step = require("step");

  /*
   connects to the database
  */


  module.exports = function(options, next) {
    if (!~options.db.indexOf("mongodb://")) {
      options.db = "mongodb://127.0.0.1:27017/" + options.db;
    }
    console.log("connecting to %s", options.db);
    return client.connect(options.db, next);
  };

}).call(this);
