// Generated by CoffeeScript 1.7.0
(function() {
  var client, connect, memoize, mongodb, step, _log;

  mongodb = require("mongodb");

  client = mongodb.MongoClient;

  step = require("step");

  memoize = require("memoizee");

  _log = require("./log");


  /*
   connects to the database
   */

  connect = memoize((function(db, next) {
    if (!~db.indexOf("mongodb://")) {
      db = "mongodb://127.0.0.1:27017/" + db;
    }
    _log("connecting to %s", db);
    return client.connect(db, next);
  }), {
    async: true
  });

  module.exports = function(options, next) {
    return connect(options.db, next);
  };

}).call(this);
