// Generated by CoffeeScript 1.7.0
(function() {
  module.exports = function() {
    if (['true', true, 1].indexOf(process.env.LOG_LIBRETTO) !== -1) {
      return console.log.apply(console, arguments);
    }
  };

}).call(this);
