// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = function() {
    if (!/true/.test(String(process.env.LOG_LIBRETTO))) {
      return;
    }
    return console.log.apply(console, arguments);
  };

}).call(this);
