// Generated by CoffeeScript 1.7.0
(function() {
  var verify;

  verify = require("verify");


  /*
   validates options for import / export
   */

  module.exports = function(options, next) {
    if (!verify().that(options).onError(next).has("path", "db").success) {
      return;
    }
    options.path = options.path.replace("~", process.env.HOME);
    return next();
  };

}).call(this);
